compute:

  train:
    name: electric-sheep
    instance: g4dn.12xlarge
    framework: lightning
    actions:
      on_build_start:
        - apt-get update
        - apt-get install ffmpeg libsm6 libxext6
